spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
     ddl-auto: update
  datasource:
    url: jdbc:mysql://47.105.103.82:3306/crystal?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 1234567890
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 20
      validation-query: SELECT 1
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 300000
      numTestsPerEvictionRun: 50
      minEvictableIdleTimeMillis: 3600000
      min-idle: 5
      max-idle: 50
      max-wait-millis: 10000
logging:
  level:
    com.yc: info
    org.hibernate.SQL: debug
